# Generated by Django 4.2.20 on 2025-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='no_of_dislikes',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
